version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/node-app
hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: ubuntu
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ubuntu

